### PR TITLE
Add Ability to setup custom user-agent

### PR DESCRIPTION
**Pull request by zyuhel**
Sometimes rss feed are not returned for non popular user agents,  so having ability to setup arbitrary user-agent will help

### CODE REVIEW

**Comment by dg** [comment]
Can you add some default value?

**Comment by juno-w** [comment]
What about by default `public static $userAgent = 'FeedFetcher-Google';` ?

**Comment by dg** [comment]
Ok

**Comment by zyuhel** [comment]
Done, IMO it will be better to set it to something like FeedFetcher dg/rss-php and put a link to github. It won't be good to bypass limitations, but it will be fair.

**Comment by dg** [comment]
Thanks

**Pull request merged**
